import FWCore.ParameterSet.Config as cms

tapTreeProducer = cms.EDProducer('TAPtreeProducer',
    	HTJets          = cms.InputTag('patJetsAK5PFPt50Eta25'),
	MetTag		= cms.InputTag('patMETsPF'),
	IsoMuonTag		= cms.InputTag('patMuonsPFIDIso'),
	IsoElecTag		= cms.InputTag('ra2ElectronsIDIso'),
	RecoMuonTag		= cms.InputTag('patMuonsPFID'),
	RecoElecTag		= cms.InputTag('ra2ElectronsID'),
	PromtMuonTag		= cms.InputTag('muons'),
	PromtElecTag		= cms.InputTag('correctedMulti5x5SuperClustersWithPreshower'),
	GsfElecTag		= cms.InputTag('gsfElectrons'),
	EventWeightTag	= cms.InputTag("WeightProducer:weight"),
	MhtTag		= cms.InputTag('mhtPF'),
	CaloJetTag	= cms.InputTag('cleanPatJetsAK5Calo'),
	MTWMax		= cms.double('100'),
	MTWCut		= cms.bool(True),
	MinMuPT		= cms.double('10'),
	MinElecPT	= cms.double('10'),
        HTTag	   	= cms.InputTag('htInputCol'),
        MHTTag	   	= cms.InputTag('mhtInputCol'),
        VertexCollection= cms.InputTag('goodVertices'),
	MuElecIdIso     = cms.uint32(0),
)
