import FWCore.ParameterSet.Config as cms

tapTreeProducer = cms.EDProducer('TAPtreeProducer',
    	HTJets          = cms.InputTag('patJetsAK5PFPt50Eta25'),
	MetTag		= cms.InputTag('patMETsPF'),
	IsoMuonTag		= cms.InputTag('patMuonsPFIDIso'),
	IsoElecTag		= cms.InputTag('ra2ElectronsIDIso'),
	RecoMuonTag		= cms.InputTag('patMuonsPFID'),
	RecoElecTag		= cms.InputTag('ra2ElectronsID'),
	PromtMuonTag		= cms.InputTag('muons'),
	PromtElecTag		= cms.InputTag('correctedMulti5x5SuperClustersWithPreshower'),
	GsfElecTag		= cms.InputTag('gsfElectrons'),
	EventWeightTag	= cms.InputTag("WeightProducer:weight"),
	MhtTag		= cms.InputTag('mhtPF'),
	CaloJetTag	= cms.InputTag('cleanPatJetsAK5Calo'),
	MTWMax		= cms.double('100'),
	MTWCut		= cms.bool(True),
	MinMuPT		= cms.double('10'),
	MinElecPT	= cms.double('10'),
        HTTag	   	= cms.InputTag('htInputCol'),
        MHTTag	   	= cms.InputTag('mhtInputCol'),
  	MuonSource   = cms.InputTag('patMuonsWithTrigger'),
	MuonTrigger     =cms.string('HLT_IsoMu24_v*'),
        VertexCollection= cms.InputTag('goodVertices'),
	MuElecIdIso     = cms.uint32(0),
  	VertexSource = cms.InputTag('goodVertices'),
  	MinMuPt      = cms.double(10),
  	MaxMuEta     = cms.double(2.4),
  	MaxMuD0      = cms.double(0.2),
  	MaxMuDz      = cms.double(0.5),
  	MaxMuRelIso  = cms.double(0.20),
  	MinMuNumHit  = cms.double(11),
	oldMethod    = cms.bool(False),
  	ElectronSource    = cms.InputTag('gsfElectrons'),
  	ConversionsSource = cms.InputTag("allConversions"),
  	BeamSpotSource    = cms.InputTag("offlineBeamSpot"),
  	RhoIsoSource      = cms.InputTag("kt6PFJets", "rho"),
  	IsoValInputTags   = cms.VInputTag(cms.InputTag('elPFIsoValueCharged03PFIdPFIso'),
                                    cms.InputTag('elPFIsoValueGamma03PFIdPFIso'),
                                    cms.InputTag('elPFIsoValueNeutral03PFIdPFIso')),
  	MinElePt       = cms.double(10),
  	MaxEleEta      = cms.double(2.5),
	MC		= cms.bool(True),
	Muon	       = cms.bool(True),
	HLTTriggerTag  = cms.InputTag('hltEle22WP90RhoEcalIsoFilter::HLT'),
#	HLTTriggerTag  = cms.InputTag('HLT_Ele27_WP80_v11::HLT'),
	trgEvtObjTag   = cms.InputTag('hltTriggerSummaryAOD::HLT'),
	HLTTriggerResultTag = cms.InputTag("TriggerResults::HLT"),
)
